site_name: MassTimber wiki
site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: imagesL0/Logo LTS.jpg
  palette:
    #Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    #Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features: 
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    #toc.integrate #plaatst paginainhoud links in toc, ipv apart rechts
    - navigation.top
    - search.suggest
    - search.higlight
    - search.share
    - content.code.copy

plugins:
  - search
  - tags

markdown_extensions: #Kleur in code snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - About: about.md
  - Controles houtsectie:
    - Normen - bronnen: controleHoutsectie/Normen-bronnen.md
    - Rekenkundige factoren: controleHoutsectie/factoren.md
    - Schuifspanning: controleHoutsectie/schuifspanning.md
  - Verbindingen:
    - Richtlijnen verbindingen: verbindingen/richtlijnen.md
    - Randafstanden: verbindingen/randafstanden.md
  - CW Plugins:
    - Labeling: CWPlugins/labeling.md
  - Tags: tags.md
  - mkDocs handleiding: mkDocs-guide.md
